<?php

/**
 * @var \Nessmodule\Request\Block\Pagedemo $block
 */

echo $block->showContent();
?>

<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .post-id{width:2%} .post-name{width:30%}

</style>

<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Request</th>
    </tr>
    <?php
    foreach ($block->getRequestData() as $key=> $row){
        echo '<tr>
                    <td>'.$row->getData('id').'</td> 
                    <td>'.$row->getMessage().'</td>
                  </tr>';
    }
    ?>
</table>

</body>
</html>


